### PR TITLE
Close local session instances on exit.

### PR DESCRIPTION
**Pull request by pareshverma91**
The session instances being created locally end up creating their own
socket connections, which get cleanup properly iff the sessions are
closed properly. None of the instances have session objects that are
being reused, hence it is safe to close them.

### CODE REVIEW

**Comment by pareshverma91** [comment]
I am having some trouble running tests locally, so am not able fix/understand the unittest error. I am pretty confident about the correctness (because the it works if I update the file in my project which is using azure python sdk, the stuff works quite well). Also, the package dependencies are missing and installing stuff as I encounter an error doesn't works quite well and I get an exception """AdalError('You hacker',)""".
It would be great if you could either verify the change yourself, or at least provide some instructions on how to get up and running.
Thanks for your time.

**Comment by lmazuel** [comment]
Hi @pareshverma91 
The tests are failing because we mock the `Session` object and don't expect to use it as a context manager. Your PR needs to fix the tests one way or another with in mind that `Session` is used with `with`.
Looks good to me as well, but I need time to check 100% that everything is ok everywhere (this code is the foundation of the SDK and the Python CLI 2.0 for Azure) in all Python versions. The person who wrote this particular file is on another project now, I'm not sure I can get time to look at.
If you can find time to fix the mock files it would help. As for the dependencies, it's the `dev_requirements.txt` file (pip install -r dev_requirements.txt).
Thank you for your feedback!

**Comment by pareshverma91** [comment]
Ah. I was thrown off by the "-e ." in dev-requirements.txt. Your comments helped.

**Comment by pareshverma91** [comment]
@lmazuel Just a gentle reminder. Consider looking at this whenever you have spare time.

**Comment by lmazuel** [comment]
Hi @pareshverma91 , just to confirm I don't forget this PR at all :)

**Pull request merged**
